### PR TITLE
drone caching

### PR DESCRIPTION
**Pull request by alandefreitas**

### CODE REVIEW

**Comment by alandefreitas** [comment]
@sdarwin You might want to have a look at what this ended up looking like. However, I'm under the impression that the rebuild-cache step is still not really uploading the directory because of some authentication issue.

**Comment by sdarwin** [comment]
> not really uploading the directory

It uploaded the cache, 1.2GB in 18 seconds, around 500mbps.

**Comment by alandefreitas** [comment]
```
level=info name=drone-cache ts=2023-03-03T18:48:05.851103433Z caller=rebuilder.go:92 component=plugin component=rebuilder msg="cache built" took=18.705754419s
```

:smile:

**Comment by alandefreitas** [comment]
If I understand that message well, it's uploading more than it should:

Clang 15 [says](https://drone.cpp.al/CPPAlliance/BoostServerTech/4/2/3)

```
drone_cache_rebuild=false
```

but the next step also says

```
level=info name=drone-cache ts=2023-03-03T18:49:45.260285085Z caller=rebuilder.go:92 component=plugin component=rebuilder msg="cache built" took=10.097202192s
```

**Comment by alandefreitas** [comment]
That's the error I got before just came back:

https://drone.cpp.al/CPPAlliance/BoostServerTech/6/1/2

```
level=error name=drone-cache ts=2023-03-03T19:58:52.859797601Z caller=main.go:628 err="[IMPORTANT] restore cache, restore failed, download from <BoostServerTech/CPPAlliance-BoostServerTech-develop-amd64-cppalliance-droneubuntu2204-1/cache> to <cache>, extract files from downloaded archive, pipe reader failed, tar reader <get file from storage backend, pipe writer failed, storage backend get failure, get the object, NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: SJ10E9GXF9C8DZN1, host id: SGzbyO1caXetNP7DNI+ubzWE+gSyR2sklUqZkTyOo7jaqPz5bC+nEs953Y5LtQmmoVH3odsy5YQ=>, archive not readable\n"
```

**Comment by sdarwin** [comment]
Just modified the cache key to in include `{{ arch }}` , since arm64 and s390x would otherwise be the same, and they should be distinguished.

> Clang 15 [says](https://drone.cpp.al/CPPAlliance/BoostServerTech/4/2/3) drone_cache_rebuild=false  but the next step also says

Made an update, try it again.

**Comment by alandefreitas** [comment]
https://drone.cpp.al/CPPAlliance/BoostServerTech/7/1/2 managed to restore the cache now. I don't know if that's something intermittent or something that got fixed with this new update.

I put `cppalliance/droneubuntu2204:multiarch` in the images that don't support caching.

```python
def image_supports_caching(image_str):
    return image_str not in [
        'cppalliance/droneubuntu2204:multiarch',
        'cppalliance/dronevs2022',
        'cppalliance/dronevs2019',
        'cppalliance/dronevs2017',
        'cppalliance/dronevs2015']
```

Let me try that again.

**Comment by alandefreitas** [comment]
https://drone.cpp.al/CPPAlliance/BoostServerTech/7/1/3 got a cache hit now. It went from 7 to 3 minutes. This is a pretty good result considering this job still installs c++12 with apt-get. It would be good if the image included `g++-12` because there's no possible world where we don't need g++12.

On the other hand, the jobs are still uploading the cache when drone_cache_rebuild=false.

**Comment by alandefreitas** [comment]
The `restore-cache` step doesn't work for s390x. https://drone.cpp.al/CPPAlliance/BoostServerTech/8/5/2

Only arm64.

**Comment by alandefreitas** [comment]
`image_supports_caching` needs to be replaced with something that considers the architecture

**Comment by sdarwin** [comment]
> doesn't work for s390x

That makes sense. meltwater hasn't published an s390x version of their plugin.

**Comment by alandefreitas** [comment]
Updated

```python
def image_supports_caching(image_str, compiler_str):
    return not (image_str.startswith('cppalliance/dronevs') or compiler_str.startswith('s390x-'))
```

**Pull request merged**
